import ThemeRegistry from '@/ThemeRegistry';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { Toolbar } from '@mui/material';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  	title: "Create Next App",
  	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  	return (
		<html lang="en">
			<body className={montserrat.className}>
				<ThemeRegistry options={{ key: 'mui' }}>
				{/* <Header /> */}
				<Toolbar>
					{children}
				</Toolbar>
				<Footer />
				</ThemeRegistry>
			</body>
		</html>
  	);
}
